### PR TITLE
61: Add database diagram and short description

### PR DESCRIPTION
**Pull request by malsolec**
#61 
I added database diagram, which we discussed on last meetings. I hope I didn't miss anything. Please add you feedback in comments that we could work out common vision.

### CODE REVIEW

**Comment by DragoonAethis** [comment]
Sorry for the delays (and missing the meeting...), had a lot of work in recent weeks. Few notes:

- Active plan's task - Plan's task should be N - 1 (instead of 1 - N - a single task may be active multiple times, a single "active" entry can't point at multiple tasks at the same time).
- `is_active` under Child plan could be a property for Child instead (as ID our currently enabled plan) - this way you always get only one ID and no additional constraints are needed.
- Can the child just start the break whenever he wants? This doesn't seem to be bounded anywhere in the active plans.
- Media storage: The current solution (keeping file paths wherever any asset is needed) doesn't exactly scale well.

I've been building a better asset importer/exporter for the linker, so that plans can be easily backed up and restored to different devices. A very similar solution could be used here:

- `media` table is used. Each entry contains `id`, `hash` (MD5 hash of the chosen file), `mime` (MIME type for that file). When adding a new file to the storage, the hash is calculated, MIME is figured out, and that file is copied to the app's internal storage (under /files/media) with the new name being `hash.mime`, `mime` being the extension derived from the MIME type. (Android downloads can mess up extensions, and while some files can be opened perfectly well without such extensions just by knowing the MIME type, such files may be not read correctly by some libraries - better to fix the extension ourselves).
- Whenever any asset is referenced in other tables, ID of the chosen media file should be kept in that table instead of the file path. Whenever any asset is required to be loaded, a separate utility class can resolve each file ID to its actual path, load it and return the loaded resource/path if needed. This should keep most (rather nasty) IO exception handling in a single class.
- Picking a new media file first opens a view with our media storage gallery. New files can be added with a **+** somewhere on the Action Bar, and the actual file system should be rarely shown (only to add new files). Database can be easily cleaned up by counting references to file IDs and removing those not used anywhere.
- This makes backups and syncing very, very easy - download the remote database, diff local vs remote, download missing assets, delete no longer used ones. Local backups can just copy the whole media storage and keep all files in a single directory, then upload only the needed files - duplicates are reused, as names being the file hashes keep them all unique. (Collisions = yeah, there's a minor, minor chance... but then, SHA-1 can be used, too, and that chance drops to almost 0.)

**Comment by malsolec** [comment]
1) You're right with N-1 - mistake, will be fixed.
2) In my opinion it could be both I'd rather choose current version, because it fits more in logical context.
3) A set of breaks are assigned to the plan and subset of them is selected randomly to be able to be choosen by the child every time the teacher decide. So it is not ordered step, as you noticed.
4) Good point. Media storage will be designed with the other task I think.

**Comment by malsolec** [comment]
2. I don't think extracting these fields to separated Configuration is a good idea, it can be problem with managing it.
5. Good idea, please, could you write a note on wiki?

Other changes were applied.

**Comment by Artem3** [comment]
Come up with 2 other things:
1. Mikolay, could you add this point to Wiki or ReadMe (what place is better ?)
> 
    I think we should change all names (attributes, relations) so that they fit snake_case. I'd like to propose such conventions:
       Database: snake_case
       Android (class): PascalCase
       Android (field, method): camelCase

2. Do we need **Date_Of_Birth** field in Child table? Should you add it to the diagram ?

**Comment by mikolevy** [comment]
@Artem3 
1. I will and I think Wiki is better place (btw. your tutorial about cloning and running project is really great! :) )
2. I think we don't need that information now - first and last name should be enough to identify child. Maybe some day it will be needed but we can always extend our db.

@malsolec 
2. Ok
3. I guess you thought about 5, yes? :)

**Pull request merged**
